[package]
name = "sra-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
libc = "0.2.169"
num_cpus = "1.16.0"
parking_lot = "0.12.3"

[build-dependencies]
pkg-config = "0.3.31"
