[package]
name = "xsra"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
gzp = "0.11.3"
libc = "0.2.169"
num_cpus = "1.16.0"
parking_lot = "0.12.3"
zstd = "0.13.2"

[build-dependencies]
pkg-config = "0.3.31"
