name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    needs: [build]
    name: CI
    runs-on: "ubuntu-latest"
    steps:
      - name: Done
        run: exit 0

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure GitHub SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host github.com" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Verify SSH connection
        run: ssh -T git@github.com || true # Will exit with error code 1 even when successful

      - name: Setup Cargo Config for SSH
        run: |
          mkdir -p ~/.cargo
          printf "[net]\ngit-fetch-with-cli = true\n" > ~/.cargo/config.toml

      - name: Build
        run: |
          # Print debugging info to see what's happening
          git config --global --list
          cargo build --verbose
