name: Rust CI

# Run this workflow on pull requests targeting main and on pushes to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  ci:
    needs: [build, test]
    name: CI
    runs-on: "ubuntu-latest"
    steps:
      - name: Done
        run: exit 0

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo test --verbose

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cargo build --verbose